import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className='sticky top-0 max-w-3xl mx-auto p-4'>
      <Navbar/>
      </div>
      <div className='mt-8 mx-8'>
      {children}
      </div>
      </body>
    </html>
  )
}
